version: '3.9'

services:

  redis:
    container_name: redis
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  postgres:
    container_name: postgres
    image: postgres:15.1
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./server/.env.docker


volumes:
  redisdata:
  pgdata:
