version: '3.9'

services:

  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  postgres:
    image: postgres:15.1
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./server/.env.docker

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    env_file:
      - ./server/.env.docker
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - redis
      - postgres

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    env_file:
      - ./client/.env.docker
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - server


volumes:
  redisdata:
  pgdata: